# Configuration of our Database
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
   <<: *default
   database: db/development.sqlite3
  # adapter: postgresql
  # host: localhost
  # port: 5432
  # database: sinatra
  # username: postgres
  # password: 4477

production:
  <<: *default
  database: db/development.sqlite3
  

test:
  <<: *default
  database: db/test.sqlite3